In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import networkx as nx

In [2]:
W = pd.read_csv("/kaggle/input/da324dataminingproject2/adjacency.csv")
W.head()

,0,1,2,3,4,5,6,7,8,9,...,11942,11943,11944,11945,11946,11947,11948,11949,11950,11951
0,0,1,0,0,1,1,0,0,0,0,...,1,1,1,1,1,1,0,0,1,1
1,1,0,0,0,1,0,1,1,0,1,...,1,1,1,1,1,1,1,0,1,1
2,0,0,0,0,0,1,0,0,0,1,...,0,0,1,1,1,0,0,0,0,1
3,0,0,0,0,1,0,0,0,1,1,...,1,0,0,0,0,1,0,1,1,1
4,1,1,0,1,0,0,0,0,1,1,...,1,1,1,0,1,1,0,1,1,1

In [3]:
X = pd.read_excel("/kaggle/input/da324dataminingproject2/attributes.xlsx")
X.head()

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,-6.3128,-5.58510,-3.0679,12.9880,9.00260,-5.5361,-1.0356,10.1650,-8.6108,4.3228,...,-2.8601,-24.768,18.2130,7.3551,44.382,18.659,-6.0441,2.9410,29.0100,-32.906
1,1.3902,-0.44661,-3.7137,-12.8420,4.47870,4.8796,3.0049,-5.9097,-7.3532,13.8250,...,-29.5170,-35.920,7.0253,-12.0390,43.115,-71.516,-25.2070,-6.4823,96.8440,-67.232
2,-8.3044,-3.45690,6.5153,-12.0090,-6.76200,-1.2466,-5.9627,9.9527,-6.2527,12.3210,...,13.8550,17.979,-25.7940,16.4910,13.304,-25.527,-52.4930,79.9770,8.9831,30.085
3,-6.3335,-5.83730,-1.5020,-5.0176,6.49150,-25.8940,11.6040,5.1414,-2.5690,6.2234,...,35.8110,18.597,-27.5800,12.5700,10.744,-38.588,10.7530,2.9410,29.0100,-32.906
4,5.6422,-2.65020,4.1389,-5.6228,0.74712,2.7475,-6.3798,9.0944,-13.5540,10.9460,...,7.1254,-38.921,-67.4780,29.1870,27.917,13.592,19.5940,31.2670,7.3044,-84.121

In [ ]:
# Create a graph from the adjacency matrix
G = nx.Graph()
edges = np.transpose(np.nonzero(W))
G.add_edges_from(edges)


# 1. Node Degree
node_degree = dict(G.degree())

# 2. Node Centrality
# # 2.1 Eigenvector Centrality
eigenvector_centrality = nx.eigenvector_centrality_numpy(G)

# # 2.2 Betweenness Centrality
betweenness_centrality = nx.betweenness_centrality(G)

# # 3. Clustering Coefficient
# clustering_coefficient = nx.clustering(G)

# 4. Graphlets (Graphlet Degree Vector - GDV)
# Function to compute GDV for a given node
def compute_gdv(graph, node):
    gdv = nx.graphlets.graphlet_degree_vector(graph, node)
    return gdv

# Create lists to store feature values
node_degrees = [node_degree[node] for node in X.index]
eigenvector_centralities = [eigenvector_centrality[node] for node in X.index]
betweenness_centralities = [betweenness_centrality[node] for node in X.index]
# clustering_coefficients = [clustering_coefficient[node] for node in X.index]
# gdvs = [compute_gdv(G, node) for node in X.index]

# Add new columns to the feature dataframe
X[103] = node_degrees
X[104] = eigenvector_centralities
X[105] = betweenness_centralities
# X['Clustering Coefficient'] = clustering_coefficients

# Convert GDV lists to DataFrame and merge with X
# gdv_df = pd.DataFrame(gdvs, index=X.index)
# X = pd.concat([X, gdv_df], axis=1)

In [ ]:
X

In [ ]:
from sklearn.cluster import AffinityPropagation
import numpy as np

clustering = AffinityPropagation(random_state=5).fit(X)
clustering.labels_

In [ ]:
sub = pd.DataFrame(clustering.labels_).reset_index()
sub = sub.rename(columns = {'index': 'ID', 0: 'LABEL'})
sub

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(X)

In [36]:
pd.DataFrame(scaled_data)

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,103
0,-0.977453,-0.841043,-0.822752,2.169179,1.581002,-0.439357,-0.366273,1.095636,-0.753976,0.136211,...,-1.049524,0.911555,0.420295,2.085849,0.918056,-0.205158,-0.380383,0.643684,-0.504979,-0.229799
1,0.641847,0.241585,-0.944762,-1.124278,0.753054,0.324054,0.098273,-1.039868,-0.570810,1.165563,...,-1.558004,0.402434,-0.464219,2.028344,-3.168008,-1.072877,-0.610868,1.943576,-1.350946,0.238046
2,-1.396121,-0.392653,0.987781,-1.018066,-1.304178,-0.124961,-0.932754,1.067432,-0.410526,1.002638,...,0.899545,-1.091081,0.836959,0.675315,-1.084127,-2.308419,1.503847,0.259911,1.047439,-1.210933
3,-0.981805,-0.894179,-0.526910,-0.126627,1.121429,-1.931476,1.086933,0.428257,0.125993,0.342099,...,0.927723,-1.172357,0.658133,0.559124,-1.675955,0.555434,-0.380383,0.643684,-0.504979,0.167443
4,1.535690,-0.222689,0.538813,-0.203793,0.070114,0.167783,-0.980709,0.953408,-1.473937,0.853687,...,-1.694836,-2.988003,1.415990,1.338554,0.688457,0.955765,0.312445,0.227743,-1.767177,1.166025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947,1.282568,0.271630,0.644121,-0.060579,-0.286516,1.450397,-0.503459,-2.521172,-0.486321,0.042356,...,1.038930,-1.640626,-1.050593,-1.249227,1.748319,-0.137522,1.005616,-0.598777,0.217306,0.721309
11948,0.261269,0.277837,-0.814761,1.363512,1.048040,1.506614,1.163390,-0.177261,1.062763,-2.398419,...,1.322716,-0.851258,0.225118,-0.891623,-0.066379,0.148945,-0.610868,1.943576,-1.350946,-0.674109
11949,-0.807262,-0.770989,-0.553285,0.212498,-1.319698,-0.670770,2.066844,-0.395299,1.867592,-0.028729,...,-0.394727,-0.252629,-0.568660,0.092611,0.800152,-0.050736,-0.380383,0.643684,-0.504979,-0.174615
11950,-0.085902,1.534486,0.165038,-1.245280,-1.195210,-0.247209,-1.137980,0.654113,-0.593429,0.818697,...,0.398223,-1.207534,1.291574,0.666600,0.365301,0.366806,1.005616,-0.598777,0.217306,1.107190
11951,0.507931,-2.052911,0.105960,0.109143,-1.245540,-0.840710,2.027753,-0.256330,2.110283,-0.017712,...,-0.889848,-0.308170,1.797907,-1.230936,-0.261658,1.617459,0.312445,0.227743,-1.767177,0.834517

In [ ]:
# Elbow method to find optimal number of clusters
wcss = []  # Within cluster sum of squares

for i in range(1, 20):
    kmeans = KMeans(n_clusters=i, init='k-means++', max_iter=300, n_init=10, random_state=0)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

In [ ]:
# Plotting the elbow method
plt.figure(figsize=(10, 6))
plt.plot(range(1, 20), wcss, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')  # Within cluster sum of squares
plt.show()

# # From the plot, we can see the elbow point, suggesting the optimal number of clusters.
# # Let's choose that and perform clustering.
# optimal_num_clusters = 4

# # Applying k-means clustering with the optimal number of clusters
# kmeans = KMeans(n_clusters=optimal_num_clusters, init='k-means++', max_iter=300, n_init=10, random_state=0)
# kmeans.fit(X)

# # Visualizing the clusters
# plt.figure(figsize=(10, 6))
# plt.scatter(X[:, 0], X[:, 1], c=kmeans

In [29]:
optimal_num_clusters = 10

# Applying k-means clustering with the optimal number of clusters
kmeans = KMeans(n_clusters=optimal_num_clusters, init='k-means++', max_iter=300, n_init=10, random_state=0)
labels = kmeans.fit_predict(scaled_data)

In [30]:
labels

array([0, 0, 0, ..., 1, 0, 1], dtype=int32)

In [31]:
sub = pd.DataFrame(labels).reset_index()
sub = sub.rename(columns = {'index': 'ID', 0: 'LABEL'})
sub

          ID  LABEL
0          0      0
1          1      0
2          2      0
3          3      1
4          4      0
...      ...    ...
11947  11947      2
11948  11948      2
11949  11949      1
11950  11950      0
11951  11951      1

[11952 rows x 2 columns]

In [32]:
sub.to_csv('submission.csv', index = False)