In [1]:
import pandas as pd

In [2]:
adjacency = pd.read_csv('/kaggle/input/da324dataminingproject2/adjacency.csv')

In [4]:
adjacency

,0,1,2,3,4,5,6,7,8,9,...,11942,11943,11944,11945,11946,11947,11948,11949,11950,11951
0,0,1,0,0,1,1,0,0,0,0,...,1,1,1,1,1,1,0,0,1,1
1,1,0,0,0,1,0,1,1,0,1,...,1,1,1,1,1,1,1,0,1,1
2,0,0,0,0,0,1,0,0,0,1,...,0,0,1,1,1,0,0,0,0,1
3,0,0,0,0,1,0,0,0,1,1,...,1,0,0,0,0,1,0,1,1,1
4,1,1,0,1,0,0,0,0,1,1,...,1,1,1,0,1,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947,1,1,0,1,1,0,0,1,1,1,...,1,1,1,1,1,0,1,1,1,1
11948,0,1,0,0,0,0,0,1,0,0,...,1,1,0,1,0,1,0,0,1,0
11949,0,0,0,1,1,0,0,0,1,1,...,1,0,0,0,0,1,0,0,1,0
11950,1,1,0,1,1,1,0,0,1,1,...,1,1,1,1,1,1,1,1,0,1
11951,1,1,1,1,1,0,0,0,0,1,...,1,1,1,1,1,1,0,0,1,0

In [5]:
adjacency.shape

(11952, 11952)

In [7]:
attributes = pd.read_excel('/kaggle/input/da324dataminingproject2/attributes.xlsx')

In [8]:
attributes

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,102
0,-6.31280,-5.58510,-3.0679,12.9880,9.00260,-5.5361,-1.0356,10.165000,-8.6108,4.3228,...,-2.8601,-24.768,18.2130,7.3551,44.38200,18.6590,-6.0441,2.9410,29.0100,-32.9060
1,1.39020,-0.44661,-3.7137,-12.8420,4.47870,4.8796,3.0049,-5.909700,-7.3532,13.8250,...,-29.5170,-35.920,7.0253,-12.0390,43.11500,-71.5160,-25.2070,-6.4823,96.8440,-67.2320
2,-8.30440,-3.45690,6.5153,-12.0090,-6.76200,-1.2466,-5.9627,9.952700,-6.2527,12.3210,...,13.8550,17.979,-25.7940,16.4910,13.30400,-25.5270,-52.4930,79.9770,8.9831,30.0850
3,-6.33350,-5.83730,-1.5020,-5.0176,6.49150,-25.8940,11.6040,5.141400,-2.5690,6.2234,...,35.8110,18.597,-27.5800,12.5700,10.74400,-38.5880,10.7530,2.9410,29.0100,-32.9060
4,5.64220,-2.65020,4.1389,-5.6228,0.74712,2.7475,-6.3798,9.094400,-13.5540,10.9460,...,7.1254,-38.921,-67.4780,29.1870,27.91700,13.5920,19.5940,31.2670,7.3044,-84.1210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947,4.43810,-0.30401,4.6963,-4.4996,-1.20150,20.2470,-2.2288,-17.060000,-6.7731,3.4564,...,-49.0210,21.036,-37.8700,-24.8960,-29.09900,36.9820,-4.5504,59.6070,-35.8270,-3.5985
11948,-0.42021,-0.27455,-3.0256,6.6693,6.09050,21.0140,12.2690,0.583450,3.8628,-19.0750,...,2.7332,27.260,-20.5240,3.0756,-21.22000,-3.0664,1.7760,-6.4823,96.8440,-67.2320
11949,-5.50320,-5.25260,-1.6416,-2.3579,-6.84680,-8.6934,20.1270,-1.057800,9.3887,2.8002,...,24.6390,-10.407,-7.3694,-14.3290,0.46541,16.0570,-2.6338,2.9410,29.0100,-32.9060
11950,-2.07170,5.68990,2.1605,-13.7910,-6.16660,-2.9145,-7.7477,6.841500,-7.5085,10.6230,...,-7.2162,6.984,-28.3530,26.4590,13.11200,6.4603,6.5873,59.6070,-35.8270,-3.5985
11951,0.75316,-11.33700,1.8478,-3.1685,-6.44160,-11.0120,19.7870,-0.011729,11.0550,2.9019,...,-27.9770,-21.266,-8.5899,37.5610,-28.69600,-7.3760,34.2070,31.2670,7.3044,-84.1210

In [21]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

adjacency = pd.read_csv('adjacency.csv', index_col=0)
seed = pd.read_excel('seed.xlsx', header=None)
attributes = pd.read_excel('attributes.xlsx')

attributes.reset_index(drop=True, inplace=True)

seed_data = []
for i in range(seed.shape[1]):
    indices = seed[i].values
    seed_data.append(attributes.loc[indices].mean().values)
seed_data = pd.DataFrame(seed_data)

attributes_with_seed = pd.concat([attributes, seed_data])

data_for_clustering = attributes_with_seed.iloc[:10952]

random_indices = np.random.choice(
    data_for_clustering.index, size=10, replace=False)
initial_centers = data_for_clustering.loc[random_indices]

kmeans = KMeans(n_clusters=10, init=initial_centers, n_init=1, random_state=42)

kmeans.fit(data_for_clustering)

cluster_labels = kmeans.labels_

attributes['Cluster'] = np.nan
attributes.loc[:10951, 'Cluster'] = cluster_labels

attributes.to_csv('attributes_with_clusters.csv', index=False)

print("Clustering completed for the first 10952 rows, and results saved to 'attributes_with_clusters.csv'.")

Clustering completed for the first 10952 rows, and results saved to 'attributes_with_clusters.csv'.

In [22]:
attributes

,0,1,2,3,4,5,6,7,8,9,...,94,95,96,97,98,99,100,101,102,Cluster
0,-6.31280,-5.58510,-3.0679,12.9880,9.00260,-5.5361,-1.0356,10.165000,-8.6108,4.3228,...,-24.768,18.2130,7.3551,44.38200,18.6590,-6.0441,2.9410,29.0100,-32.9060,2.0
1,1.39020,-0.44661,-3.7137,-12.8420,4.47870,4.8796,3.0049,-5.909700,-7.3532,13.8250,...,-35.920,7.0253,-12.0390,43.11500,-71.5160,-25.2070,-6.4823,96.8440,-67.2320,3.0
2,-8.30440,-3.45690,6.5153,-12.0090,-6.76200,-1.2466,-5.9627,9.952700,-6.2527,12.3210,...,17.979,-25.7940,16.4910,13.30400,-25.5270,-52.4930,79.9770,8.9831,30.0850,5.0
3,-6.33350,-5.83730,-1.5020,-5.0176,6.49150,-25.8940,11.6040,5.141400,-2.5690,6.2234,...,18.597,-27.5800,12.5700,10.74400,-38.5880,10.7530,2.9410,29.0100,-32.9060,2.0
4,5.64220,-2.65020,4.1389,-5.6228,0.74712,2.7475,-6.3798,9.094400,-13.5540,10.9460,...,-38.921,-67.4780,29.1870,27.91700,13.5920,19.5940,31.2670,7.3044,-84.1210,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11947,4.43810,-0.30401,4.6963,-4.4996,-1.20150,20.2470,-2.2288,-17.060000,-6.7731,3.4564,...,21.036,-37.8700,-24.8960,-29.09900,36.9820,-4.5504,59.6070,-35.8270,-3.5985,NaN
11948,-0.42021,-0.27455,-3.0256,6.6693,6.09050,21.0140,12.2690,0.583450,3.8628,-19.0750,...,27.260,-20.5240,3.0756,-21.22000,-3.0664,1.7760,-6.4823,96.8440,-67.2320,NaN
11949,-5.50320,-5.25260,-1.6416,-2.3579,-6.84680,-8.6934,20.1270,-1.057800,9.3887,2.8002,...,-10.407,-7.3694,-14.3290,0.46541,16.0570,-2.6338,2.9410,29.0100,-32.9060,NaN
11950,-2.07170,5.68990,2.1605,-13.7910,-6.16660,-2.9145,-7.7477,6.841500,-7.5085,10.6230,...,6.984,-28.3530,26.4590,13.11200,6.4603,6.5873,59.6070,-35.8270,-3.5985,NaN
11951,0.75316,-11.33700,1.8478,-3.1685,-6.44160,-11.0120,19.7870,-0.011729,11.0550,2.9019,...,-21.266,-8.5899,37.5610,-28.69600,-7.3760,34.2070,31.2670,7.3044,-84.1210,NaN

In [24]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

attributes_with_clusters = pd.read_csv('attributes_with_clusters.csv')

X = attributes_with_clusters.iloc[:, :-1]
y = attributes_with_clusters['Cluster']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=1000, random_state=42)

nan_indices = y_train.index[y_train.isna()]
X_train = X_train.drop(index=nan_indices)
y_train = y_train.drop(index=nan_indices)

mlp_classifier = MLPClassifier(hidden_layer_sizes=(
    100,), activation='relu', solver='adam', random_state=42)
mlp_classifier.fit(X_train, y_train)

predicted_labels = mlp_classifier.predict(X_test)

submission_df = pd.DataFrame(
    {'ID': range(len(predicted_labels)), 'LABEL': predicted_labels})
submission_df.to_csv('submission.csv', index=False)

print("Prediction completed for the remaining 1000 samples, and results saved to 'submission.csv'.")

Prediction completed for the remaining 1000 samples, and results saved to 'submission.csv'.

In [25]:
all_labels = np.concatenate((cluster_labels, predicted_labels))

submission_df = pd.DataFrame(
    {'ID': range(len(all_labels)), 'LABEL': all_labels})
submission_df.to_csv('submission.csv', index=False)

print("Cluster labels for all 11952 samples saved to 'submission.csv'.")

Cluster labels for all 11952 samples saved to 'submission.csv'.